### ISSUE TITLE
Backend for pure socket instruments

### ISSUE THREAD

**Issue by MatthieuDartiailh** [LabPy/lantz_core#8]
Related to https://github.com/LabPy/lantz_drivers/issues/5. The idea would to use a simple socket for communication with an instrument. It would make sense to have properties similar to the ones found in VisaMessageDriver.

**Comment by hgrecco** [comment]
VISA has the `TCPIP::*::SOCKET`. And using PyVISA you can either use NI-VISA or (soon) PyVISA-py backend (which used the python std). I think this covers it, right?

**Comment by MatthieuDartiailh** [comment]
In a way yes but it will provide things that are not available such as clear or status_byte for non Visa instruments. You are perhaps right we could go with a different subclass to hide unavailable properties but using pyvisa as a backend for communication. I need to think a bit more about this one.

**Comment by MatthieuDartiailh** [comment]
I will follow your suggestion at @hgrecco.
